# Generated by Django 5.0.7 on 2024-07-18 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_public', models.ImageField(blank=True, null=True, upload_to='publications_images')),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('informations', models.TextField(blank=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
